services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lorebound
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lorebound
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - JWT_PRIVATE_KEY_PATH=/app/secrets/jwt_private.pem
      - JWT_PUBLIC_KEY_PATH=/app/secrets/jwt_public.pem
      - APPLE_PRIVATE_KEY_PATH=/app/secrets/apple_signin_key.p8
      - DEBUG=true
      - RELOAD=true
    volumes:
      - ./app:/app/app
      - ./secrets:/app/secrets
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lorebound
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - JWT_PRIVATE_KEY_PATH=/app/secrets/jwt_private.pem
      - JWT_PUBLIC_KEY_PATH=/app/secrets/jwt_public.pem
      - APPLE_PRIVATE_KEY_PATH=/app/secrets/apple_signin_key.p8
    volumes:
      - ./app:/app/app
      - ./secrets:/app/secrets
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: poetry run celery -A app.jobs.worker worker --loglevel=info

  migrate:
    build: .
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/lorebound
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - JWT_PRIVATE_KEY_PATH=/app/secrets/jwt_private.pem
      - JWT_PUBLIC_KEY_PATH=/app/secrets/jwt_public.pem
      - APPLE_PRIVATE_KEY_PATH=/app/secrets/apple_signin_key.p8
    volumes:
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
      - ./secrets:/app/secrets
    depends_on:
      db:
        condition: service_healthy
    command: poetry run alembic upgrade head
    profiles:
      - migration

volumes:
  postgres_data:
  redis_data:
