-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4f6wX/voIcoQVMEJ
YmhKNlHolhcqQg5TsYCuOZP3G7GgCgYIKoZIzj0DAQehRANCAATx9+LIJGiM0/XH
PLACEHOLDER_APPLE_KEY_FOR_DEVELOPMENT_ONLY_DO_NOT_USE_IN_PRODUCTION
REPLACE_WITH_ACTUAL_APPLE_SIGNIN_PRIVATE_KEY_FROM_APPLE_DEVELOPER_CONSOLE
-----END PRIVATE KEY-----
